id: 08_gcp_kv
namespace: zoomcamp

inputs:
  - id: plan_type
    type: SELECT
    displayName: Select plan type
    values: [ medical, dental ]
    defaults: medical

  - id: entity_type
    type: SELECT
    displayName: Select entity type
    values: [ individual, shop ]
    defaults: individual

variables:
  plan_year:  {{ trigger.date ?? execution.startDate | date("yyyy") }}
  # file_id: "{{inputs.entity_type}}_market_{{inputs.plan_type}}"
  # gcs_file: "gs://{{kv('GCP_BUCKET_NAME')}}/{{inputs.plan_year}}/{{inputs.entity_type}}/{{inputs.plan_type}}/{{vars.file_id}}.parquet"
  # table: "{{kv('GCP_DATASET')}}.{{inputs.entity_type}}_market_{{inputs.plan_type}}_{{inputs.plan_year}}"
  # data: "{{ outputs.parquet_output.outputFiles[inputs.entity_type ~ '_market_' ~ inputs.plan_type ~ '.parquet'] }}"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      plan_year: "{{render(vars.plan_year)}}"

triggers:
  - id: individual_market_trigger
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"
    inputs:
      plan_type: medical
      entity_type: individual