name: insurance_marketplace

profile: my-bigquery-db

version: '1.0'

require-dbt-version: ">=0.14.0"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

models:
  insurance_marketplace-dbt:
      # Applies to all files under models/.../
      staging:
          materialized: view
      core:
          materialized: table

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"





