
my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile_json: "{{ env_var('DBT_BIGQUERY_TOKEN') }}" # Fetch the token from the environment variable # Fetching credentials from GitHub environment variable
      project: vibrant-mantis-376307 # Replace this with your project id
      dataset: insurance_dataset_376307 # Replace this with dbt_your_name, e.g. dbt_bob
      location: us-central1 # Replace this with your location, e.g. US, EU, asia-northeast1, etc
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive


