name: Dev build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write
  checks: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Create DBT credentials file
        run: |
          cd ./dbt/insurance-marketplace-dbt
          echo "${{ secrets.DBT_BIGQUERY_TOKEN }}" > creds.json

      - name: List folder contents
        run: |
          ls -l ./dbt/insurance-marketplace-dbt/

      - name: Install dbt packages
        run: |
          source .venv/bin/activate
          cd ./dbt/insurance-marketplace-dbt
          dbt deps
          dbt debug --connection