name: Dev build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write
  checks: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dbt packages
        run: dbt deps
        working-directory: ./dbt/insurance-marketplace-dbt

      # - name: Run dbt commands
      #   run: |
      #     dbt deps
      #     dbt run --full-refresh --vars '{"is_test_run":false}'
      #     dbt test --vars '{"is_test_run":false}'

      # - name: Upload dbt manifest
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: manifest.json